In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789
import numpy as np
import torch

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.3787, 0.1149],
        [0.4982, 0.3173]])

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.2600, 0.2974, 0.9164],
         [0.5089, 0.6982, 0.8795]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [29]:
tensor = torch.rand(3, 4)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [30]:
if torch.accelerator.is_available():
    print('Zoom!')
    tensor = tensor.to(torch.accelerator.current_accelerator())
else:
    print('Just poking along')

Zoom!


In [31]:
tensor[0]

tensor([0.1034, 0.9734, 0.4741, 0.4134], device='mps:0')

In [32]:
tensor[:, 0]

tensor([0.1034, 0.8176, 0.1675], device='mps:0')

In [33]:
tensor[..., -1]

tensor([0.4134, 0.1870, 0.5918], device='mps:0')

In [34]:
tensor[:, 1] = 0
tensor

tensor([[0.1034, 0.0000, 0.4741, 0.4134],
        [0.8176, 0.0000, 0.4800, 0.1870],
        [0.1675, 0.0000, 0.1621, 0.5918]], device='mps:0')

In [35]:
t1 = torch.cat([tensor, tensor], dim=1)
t1

tensor([[0.1034, 0.0000, 0.4741, 0.4134, 0.1034, 0.0000, 0.4741, 0.4134],
        [0.8176, 0.0000, 0.4800, 0.1870, 0.8176, 0.0000, 0.4800, 0.1870],
        [0.1675, 0.0000, 0.1621, 0.5918, 0.1675, 0.0000, 0.1621, 0.5918]],
       device='mps:0')

In [38]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
y3 == y1, y1 == y2

(tensor([[True, True, True],
         [True, True, True],
         [True, True, True]], device='mps:0'),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]], device='mps:0'))

In [37]:
z1  = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
z1 == z3, z2 == z1

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]], device='mps:0'),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]], device='mps:0'))

In [23]:
agg = tensor.sum()
agg.item(), type(agg.item())

(4.285228729248047, float)

In [24]:
tensor.add_(5)  # inplace
tensor

tensor([[5.1253, 5.0000, 5.5510, 5.6904],
        [5.8879, 5.0000, 5.1863, 5.7305],
        [5.5890, 5.0000, 5.1202, 5.4046]], device='mps:0')

In [25]:
tensor -= 5
tensor

tensor([[0.1253, 0.0000, 0.5510, 0.6904],
        [0.8879, 0.0000, 0.1863, 0.7305],
        [0.5890, 0.0000, 0.1202, 0.4046]], device='mps:0')