In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789
import numpy as np
import torch

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.4755, 0.5974],
        [0.4368, 0.1085]])

In [6]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.1366, 0.9233, 0.0654],
         [0.5002, 0.7903, 0.1457]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [7]:
tensor = torch.rand(3, 4)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [8]:
if torch.accelerator.is_available():
    print('Zoom!')
    tensor = tensor.to(torch.accelerator.current_accelerator())
else:
    print('Just poking along')

Zoom!


In [9]:
tensor[0]

tensor([0.4934, 0.4470, 0.7806, 0.9775], device='mps:0')

In [10]:
tensor[:, 0]

tensor([0.4934, 0.0184, 0.1485], device='mps:0')

In [11]:
tensor[..., -1]

tensor([0.9775, 0.2632, 0.3020], device='mps:0')

In [12]:
tensor[:, 1] = 0
tensor

tensor([[0.4934, 0.0000, 0.7806, 0.9775],
        [0.0184, 0.0000, 0.5563, 0.2632],
        [0.1485, 0.0000, 0.7735, 0.3020]], device='mps:0')

In [13]:
t1 = torch.cat([tensor, tensor], dim=1)
t1

tensor([[0.4934, 0.0000, 0.7806, 0.9775, 0.4934, 0.0000, 0.7806, 0.9775],
        [0.0184, 0.0000, 0.5563, 0.2632, 0.0184, 0.0000, 0.5563, 0.2632],
        [0.1485, 0.0000, 0.7735, 0.3020, 0.1485, 0.0000, 0.7735, 0.3020]],
       device='mps:0')

In [14]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
y3 == y1, y1 == y2

(tensor([[True, True, True],
         [True, True, True],
         [True, True, True]], device='mps:0'),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]], device='mps:0'))

In [15]:
z1  = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
z1 == z3, z2 == z1

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]], device='mps:0'),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]], device='mps:0'))

In [16]:
agg = tensor.sum()
agg.item(), type(agg.item())

(4.313360214233398, float)

In [17]:
tensor.add_(5)  # inplace
tensor

tensor([[5.4934, 5.0000, 5.7806, 5.9775],
        [5.0184, 5.0000, 5.5563, 5.2632],
        [5.1485, 5.0000, 5.7735, 5.3020]], device='mps:0')

In [18]:
tensor -= 5
tensor

tensor([[0.4934, 0.0000, 0.7806, 0.9775],
        [0.0184, 0.0000, 0.5563, 0.2632],
        [0.1485, 0.0000, 0.7735, 0.3020]], device='mps:0')

In [19]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [21]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [22]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [23]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
t, n

(tensor([2., 2., 2., 2., 2.], dtype=torch.float64),
 array([2., 2., 2., 2., 2.]))