In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789
import os

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
device = (
    torch.accelerator.current_accelerator().type
    if torch.accelerator.is_available()
    else 'cpu')
device

'mps'

In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10))

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [4]:
mod = NeuralNetwork().to(device)
mod

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [5]:
X = torch.rand(1, 28, 28, device=device)
logits = mod(X)
pred_prob = nn.Softmax(dim=1)(logits)
y_pred = pred_prob.argmax(1)
y_pred

tensor([2], device='mps:0')

In [6]:
input_image = torch.rand(3, 28, 28)
input_image.size()

torch.Size([3, 28, 28])

In [7]:
flatten = nn.Flatten()
flat_img = flatten(input_image)
flat_img.size()

torch.Size([3, 784])

In [8]:
layer1 = nn.Linear(in_features=28 * 28, out_features=20)
hidden1 = layer1(flat_img)
hidden1.size()

torch.Size([3, 20])

In [9]:
print(hidden1)
hidden1 = nn.ReLU()(hidden1)
print()
print(hidden1)

tensor([[ 0.4125,  0.3454,  0.1528,  0.2118, -0.3536,  0.2394,  0.2799, -0.2598,
         -0.2351,  0.3011, -0.3790,  0.6173,  0.2875, -0.6543,  0.1451,  0.2317,
         -0.5561,  0.0717, -0.0532, -0.1348],
        [ 0.5181,  0.3163,  0.0680,  0.1175, -0.1654, -0.1841,  0.1037, -0.0393,
         -0.3624,  0.2046, -0.1320,  0.1732, -0.0871, -0.7469,  0.0225,  0.1970,
         -0.5684, -0.2202,  0.1203,  0.1806],
        [ 0.2137,  0.0661, -0.0107,  0.0906, -0.2031,  0.3038,  0.1412, -0.1030,
          0.0374,  0.1118, -0.4049, -0.0788,  0.1157, -0.6448,  0.0372,  0.0874,
         -0.2638, -0.0752, -0.1707,  0.3094]], grad_fn=<AddmmBackward0>)

tensor([[0.4125, 0.3454, 0.1528, 0.2118, 0.0000, 0.2394, 0.2799, 0.0000, 0.0000,
         0.3011, 0.0000, 0.6173, 0.2875, 0.0000, 0.1451, 0.2317, 0.0000, 0.0717,
         0.0000, 0.0000],
        [0.5181, 0.3163, 0.0680, 0.1175, 0.0000, 0.0000, 0.1037, 0.0000, 0.0000,
         0.2046, 0.0000, 0.1732, 0.0000, 0.0000, 0.0225, 0.1970, 0.0000, 0.0000