In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#234567890
import numpy as np
import pandas as pd
import torch

In [2]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [3]:
x.dtype

torch.int64

In [4]:
npa = np.array([[1, 2, 3], [4, 5, 6]])
tensor = torch.from_numpy(npa)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
df = pd.read_csv('./data.csv')
df

,distance_miles,delivery_time_minutes
0,1.60,7.22
1,13.09,32.41
2,6.97,17.47


In [7]:
all_vals = df.values
tensor = torch.tensor(all_vals)
tensor

tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

In [8]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
torch.rand(2, 2)

tensor([[0.7326, 0.6476],
        [0.3473, 0.8512]])

In [11]:
torch.arange(0, 10, step=1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x = torch.tensor([[1, 2, 3], [3, 2, 1]])
x

tensor([[1, 2, 3],
        [3, 2, 1]])

In [15]:
expanded = x.unsqueeze(0)
expanded

tensor([[[1, 2, 3],
         [3, 2, 1]]])

In [16]:
expanded.shape

torch.Size([1, 2, 3])

In [17]:
expanded.squeeze()

tensor([[1, 2, 3],
        [3, 2, 1]])

In [18]:
x.reshape(3, 2)

tensor([[1, 2],
        [3, 3],
        [2, 1]])

In [21]:
x.transpose(0, 1)

tensor([[1, 3],
        [2, 2],
        [3, 1]])

In [22]:
ta = torch.tensor([[1, 2], [3, 4]])
tb = torch.tensor([[5, 6], [7, 8]])
torch.cat((ta, tb), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [23]:
torch.cat((ta, tb))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [24]:
x = torch.tensor(
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]])

In [25]:
x[1, 2]

tensor(7)

In [26]:
x[1]

tensor([5, 6, 7, 8])

In [27]:
x[-1]

tensor([ 9, 10, 11, 12])

In [28]:
x[:2]

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [29]:
x[:, 2]

tensor([ 3,  7, 11])

In [30]:
x[:, ::2]

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])

In [31]:
x[:2, 2:]

tensor([[3, 4],
        [7, 8]])

In [32]:
scalar_t = x[1, 2]
scalar_t

tensor(7)

In [34]:
scalar_t.item(), type(scalar_t.item())

(7, int)

In [35]:
mask = x > 6
x[mask]

tensor([ 7,  8,  9, 10, 11, 12])

In [37]:
i = torch.tensor([0, 2])
j = torch.tensor([1, 3])
x[i, j]

tensor([ 2, 12])

In [38]:
x[i[:, None], j]

tensor([[ 2,  4],
        [10, 12]])

In [39]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a + b

tensor([5, 7, 9])

In [40]:
a * b  # element-wise

tensor([ 4, 10, 18])

In [41]:
a @ b

tensor(32)

In [42]:
torch.matmul(a, b)

tensor(32)

In [43]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1], [2], [3]])
a + b

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [44]:
temps = torch.tensor([20, 35, 19, 35, 42])
is_hot = temps > 30
is_cool = temps <= 20
is_just_right = temps == 35
is_hot

tensor([False,  True, False,  True,  True])

In [45]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])

is_morning & is_raining

tensor([False, False, False,  True])

In [46]:
is_morning | is_raining

tensor([ True, False,  True,  True])

In [47]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
data.mean()

tensor(30.)

In [48]:
data.std()

tensor(15.8114)

In [49]:
data.int()

tensor([10, 20, 30, 40, 50], dtype=torch.int32)

In [50]:
sales_data = torch.tensor(
    [[100, 120, 130, 110],   # Product A
     [ 90,  95, 105, 125],   # Product B
     [140, 115, 120, 150]],  # Product C
    dtype=torch.float32)

In [52]:
total_sales_product_b = sales_data[1].sum()
total_sales_product_b

tensor(415.)

In [60]:
high_c = []
for i, val in enumerate(sales_data[2]):
    if val > 130:
        high_c.append(i)

print('Months where C sales > 130:', high_c)

Months where C sales > 130: [0, 3]


In [57]:
sales_data[sales_data > 130]

tensor([140., 150.])

In [61]:
sales_feb_mar = sales_data[:, 1:3]
sales_feb_mar

tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])

In [65]:
image_batch = torch.rand(4, 3, 3)
image_batch_with_channel = image_batch.unsqueeze(1)
image_batch_with_channel.shape

torch.Size([4, 1, 3, 3])

In [66]:
image_batch_transposed = image_batch_with_channel.transpose(1, 3)
image_batch_transposed.shape

torch.Size([4, 3, 3, 1])

In [73]:
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

stack = torch.cat((temperature.unsqueeze(0), humidity.unsqueeze(0)))
stack

tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000],
        [55.2000, 56.4000, 54.8000, 57.1000, 56.8000]])

In [70]:
weights = torch.tensor([0.6, 0.4])

In [71]:
weights = weights.reshape(2, 1)
weights

tensor([[0.6000],
        [0.4000]])

In [78]:
w_sum = (weights * stack).sum(0)
w_sum

tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])

In [79]:
w_avg = w_sum.sum() / len(w_sum)
w_avg

tensor(36.0800)

In [80]:
w = torch.tensor([0.6, 0.4])
w @ stack

tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])

In [81]:
trip_data = torch.tensor([
    [5.3, 7],   # Not rush hour, not long
    [12.1, 9],  # Morning rush, long trip -> RUSH HOUR LONG
    [15.5, 13], # Not rush hour, long trip
    [6.7, 18],  # Evening rush, not long
    [2.4, 20],  # Not rush hour, not long
    [11.8, 17], # Evening rush, long trip -> RUSH HOUR LONG
    [9.0, 9],   # Morning rush, not long
    [14.2, 8]   # Morning rush, long trip -> RUSH HOUR LONG
], dtype=torch.float32)

In [82]:
distances = trip_data[:, 0]
hours = trip_data[:, 1]

In [89]:
is_long_trip = distances > 10
is_morning_rush = (8 <= hours) & (hours <= 10)
is_evening_rush = (17 <= hours) & (hours <= 19)

In [90]:
is_long_rush_hour_trip = is_long_trip & (is_morning_rush | is_evening_rush)

In [94]:
trip_data[is_long_rush_hour_trip].reshape(-1, 1).float()

tensor([[12.1000],
        [ 9.0000],
        [11.8000],
        [17.0000],
        [14.2000],
        [ 8.0000]])